### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by Villanuevand** [Villanuevand/es6-with-wesbos#2]
Elegir emojis para: 

- Ir arriba
- Siguiente módulo

**Comment by jobsamuel** [comment]
Pueden ser :point_up_2: y :rocket:

**Comment by Villanuevand** [comment]
@jobsamuel si... 

Me parecen mejor ...  acabo de hacer el push de uno básico xD.. ¡¡YA LO CAMBIO!!
